# Generated by Django 4.2 on 2025-01-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_alter_service_order_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
    ]
