# Generated by Django 4.2 on 2025-01-29 19:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_service_options_remove_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='tags_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='tags_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_ar',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='subtitle_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
