# Generated by Django 4.2 on 2025-02-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_service_content_servicepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
