# Generated by Django 4.2 on 2025-02-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_service_content_ar_service_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_en',
            field=models.TextField(null=True),
        ),
    ]
