# Generated by Django 4.2 on 2025-02-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_portfolio_options_banner_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='service',
        ),
    ]
